<?php

namespace Database\Seeders;

use App\Enums\GenderEnum;
use App\Enums\ReligionEnum;
use App\Enums\RoleEnum;
use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;
use Illuminate\Support\Facades\Hash;
use Illuminate\Support\Str;

class UsersSeeder extends Seeder
{
    public function run(): void
    {
        $now = now();

        DB::table('users')->insertOrIgnore([
            [
                'id' => SeedIds::ADMIN_USER_ID,
                'name' => 'Admin',
                'email' => 'admin@example.test',
                'email_verified_at' => $now,
                'password' => Hash::make('password'),
                'role' => RoleEnum::ADMIN->value,
                'telephone_number' => '081111111111',
                'telephone_verified_at' => $now,
                'profile_photo_path' => null,
                'date_of_birth' => '1990-01-01',
                'gender' => GenderEnum::MAN->value,
                'religion' => ReligionEnum::ISLAM->value,
                'home_address' => json_encode([
                    'province' => 'DKI Jakarta',
                    'regency' => 'Jakarta Pusat',
                    'district' => 'Gambir',
                    'subdistrict' => 'Cideng',
                    'street' => 'Jl. Contoh No. 1',
                ], JSON_UNESCAPED_UNICODE),
                'google_id' => null,
                'facebook_id' => null,
                'latitude' => -6.20000000,
                'longitude' => 106.81666600,
                'remember_token' => Str::random(10),
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'id' => SeedIds::TUTOR_USER_ID,
                'name' => 'Tutor Demo',
                'email' => 'tutor@example.test',
                'email_verified_at' => $now,
                'password' => Hash::make('password'),
                'role' => RoleEnum::TUTOR->value,
                'telephone_number' => '082222222222',
                'telephone_verified_at' => $now,
                'profile_photo_path' => null,
                'date_of_birth' => '1995-06-15',
                'gender' => GenderEnum::WOMAN->value,
                'religion' => ReligionEnum::KRISTEN->value,
                'home_address' => json_encode([
                    'province' => 'Jawa Barat',
                    'regency' => 'Bandung',
                    'district' => 'Coblong',
                    'subdistrict' => 'Dago',
                    'street' => 'Jl. Mentor No. 2',
                ], JSON_UNESCAPED_UNICODE),
                'google_id' => null,
                'facebook_id' => null,
                'latitude' => -6.91474400,
                'longitude' => 107.60981000,
                'remember_token' => Str::random(10),
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'id' => SeedIds::TUTOR_USER_2_ID,
                'name' => 'Tutor Demo 2',
                'email' => 'tutor2@example.test',
                'email_verified_at' => $now,
                'password' => Hash::make('password'),
                'role' => RoleEnum::TUTOR->value,
                'telephone_number' => '082222222223',
                'telephone_verified_at' => $now,
                'profile_photo_path' => null,
                'date_of_birth' => '1994-02-11',
                'gender' => GenderEnum::MAN->value,
                'religion' => ReligionEnum::ISLAM->value,
                'home_address' => json_encode([
                    'province' => 'Jawa Barat',
                    'regency' => 'Bandung',
                    'district' => 'Sukajadi',
                    'subdistrict' => 'Pasteur',
                    'street' => 'Jl. Mentor No. 5',
                ], JSON_UNESCAPED_UNICODE),
                'google_id' => null,
                'facebook_id' => null,
                'latitude' => -6.91474400,
                'longitude' => 107.60981000,
                'remember_token' => Str::random(10),
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'id' => SeedIds::TUTOR_USER_3_ID,
                'name' => 'Tutor Demo 3',
                'email' => 'tutor3@example.test',
                'email_verified_at' => $now,
                'password' => Hash::make('password'),
                'role' => RoleEnum::TUTOR->value,
                'telephone_number' => '082222222224',
                'telephone_verified_at' => $now,
                'profile_photo_path' => null,
                'date_of_birth' => '1996-09-03',
                'gender' => GenderEnum::WOMAN->value,
                'religion' => ReligionEnum::KATOLIK->value,
                'home_address' => json_encode([
                    'province' => 'DKI Jakarta',
                    'regency' => 'Jakarta Selatan',
                    'district' => 'Kebayoran Baru',
                    'subdistrict' => 'Gandaria Utara',
                    'street' => 'Jl. Mentor No. 6',
                ], JSON_UNESCAPED_UNICODE),
                'google_id' => null,
                'facebook_id' => null,
                'latitude' => -6.20000000,
                'longitude' => 106.81666600,
                'remember_token' => Str::random(10),
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'id' => SeedIds::TUTOR_USER_4_ID,
                'name' => 'Tutor Demo 4',
                'email' => 'tutor4@example.test',
                'email_verified_at' => $now,
                'password' => Hash::make('password'),
                'role' => RoleEnum::TUTOR->value,
                'telephone_number' => '082222222225',
                'telephone_verified_at' => $now,
                'profile_photo_path' => null,
                'date_of_birth' => '1993-12-30',
                'gender' => GenderEnum::MAN->value,
                'religion' => ReligionEnum::HINDU->value,
                'home_address' => json_encode([
                    'province' => 'Jawa Barat',
                    'regency' => 'Depok',
                    'district' => 'Beji',
                    'subdistrict' => 'Kemiri Muka',
                    'street' => 'Jl. Mentor No. 7',
                ], JSON_UNESCAPED_UNICODE),
                'google_id' => null,
                'facebook_id' => null,
                'latitude' => -6.40248400,
                'longitude' => 106.79424300,
                'remember_token' => Str::random(10),
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'id' => SeedIds::TUTOR_USER_5_ID,
                'name' => 'Tutor Demo 5',
                'email' => 'tutor5@example.test',
                'email_verified_at' => $now,
                'password' => Hash::make('password'),
                'role' => RoleEnum::TUTOR->value,
                'telephone_number' => '082222222226',
                'telephone_verified_at' => $now,
                'profile_photo_path' => null,
                'date_of_birth' => '1992-04-08',
                'gender' => GenderEnum::WOMAN->value,
                'religion' => ReligionEnum::BUDDHA->value,
                'home_address' => json_encode([
                    'province' => 'Banten',
                    'regency' => 'Tangerang',
                    'district' => 'Cikokol',
                    'subdistrict' => 'Sukasari',
                    'street' => 'Jl. Mentor No. 8',
                ], JSON_UNESCAPED_UNICODE),
                'google_id' => null,
                'facebook_id' => null,
                'latitude' => -6.17830600,
                'longitude' => 106.63188900,
                'remember_token' => Str::random(10),
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'id' => SeedIds::STUDENT_USER_ID,
                'name' => 'Student Demo',
                'email' => 'student@example.test',
                'email_verified_at' => $now,
                'password' => Hash::make('password'),
                'role' => RoleEnum::STUDENT->value,
                'telephone_number' => '083333333333',
                'telephone_verified_at' => $now,
                'profile_photo_path' => null,
                'date_of_birth' => '2010-03-10',
                'gender' => GenderEnum::MAN->value,
                'religion' => ReligionEnum::ISLAM->value,
                'home_address' => json_encode([
                    'province' => 'Jawa Barat',
                    'regency' => 'Depok',
                    'district' => 'Pancoran Mas',
                    'subdistrict' => 'Depok',
                    'street' => 'Jl. Siswa No. 3',
                ], JSON_UNESCAPED_UNICODE),
                'google_id' => null,
                'facebook_id' => null,
                'latitude' => -6.40248400,
                'longitude' => 106.79424300,
                'remember_token' => Str::random(10),
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'id' => SeedIds::PARENT_USER_ID,
                'name' => 'Parent Demo',
                'email' => 'parent@example.test',
                'email_verified_at' => $now,
                'password' => Hash::make('password'),
                'role' => RoleEnum::PARENT->value,
                'telephone_number' => '084444444444',
                'telephone_verified_at' => $now,
                'profile_photo_path' => null,
                'date_of_birth' => '1985-08-21',
                'gender' => GenderEnum::WOMAN->value,
                'religion' => ReligionEnum::ISLAM->value,
                'home_address' => json_encode([
                    'province' => 'Banten',
                    'regency' => 'Tangerang',
                    'district' => 'Karawaci',
                    'subdistrict' => 'Cimone',
                    'street' => 'Jl. Orang Tua No. 4',
                ], JSON_UNESCAPED_UNICODE),
                'google_id' => null,
                'facebook_id' => null,
                'latitude' => -6.17830600,
                'longitude' => 106.63188900,
                'remember_token' => Str::random(10),
                'created_at' => $now,
                'updated_at' => $now,
            ],
        ]);
    }
}
